<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260801000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin_audit_log (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(64) NOT NULL, target_type VARCHAR(32) DEFAULT NULL, target_id INT DEFAULT NULL, payload JSON DEFAULT NULL, created_at DATETIME NOT NULL, actor_id INT DEFAULT NULL, INDEX admin_audit_actor_idx (actor_id), INDEX admin_audit_action_idx (action), INDEX admin_audit_target_idx (target_type, target_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE api_key (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, prefix VARCHAR(12) NOT NULL, token_hash VARCHAR(64) NOT NULL, scopes JSON NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME DEFAULT NULL, last_used_at DATETIME DEFAULT NULL, revoked_at DATETIME DEFAULT NULL, user_id INT NOT NULL, UNIQUE INDEX UNIQ_C912ED9DB3BC57DA (token_hash), INDEX IDX_C912ED9DA76ED395 (user_id), INDEX api_key_user_active_idx (user_id, revoked_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE appeal (id INT AUTO_INCREMENT NOT NULL, reason LONGTEXT NOT NULL, status VARCHAR(20) NOT NULL, resolved_at DATETIME DEFAULT NULL, resolution_note LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, moderation_action_id INT NOT NULL, appellant_id INT NOT NULL, resolved_by_id INT DEFAULT NULL, INDEX IDX_96794351851858D7 (appellant_id), INDEX IDX_967943516713A32B (resolved_by_id), INDEX idx_appeal_status (status), UNIQUE INDEX uniq_appeal_action (moderation_action_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE challenge (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, used_at DATETIME DEFAULT NULL, expires_at DATETIME NOT NULL, attempts INT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D7098951E7927C745F37A13B (email, token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE channel (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, position INT DEFAULT 0 NOT NULL, name VARCHAR(255) NOT NULL, is_private TINYINT DEFAULT 0 NOT NULL, archived_at DATETIME DEFAULT NULL, is_readonly TINYINT DEFAULT 0 NOT NULL, are_readonly_replies_allowed TINYINT DEFAULT 0 NOT NULL, type VARCHAR(20) NOT NULL, allow_attachments TINYINT DEFAULT 1 NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, section_id INT DEFAULT NULL, community_id INT DEFAULT NULL, INDEX IDX_A2F98E47D823E37A (section_id), INDEX IDX_A2F98E47FDA7B0BF (community_id), UNIQUE INDEX UNIQ_CHANNEL_IDENTIFIER (identifier), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE channel_member (id INT AUTO_INCREMENT NOT NULL, role VARCHAR(20) NOT NULL, added_at DATETIME NOT NULL, user_id INT NOT NULL, channel_id INT NOT NULL, INDEX IDX_8E87C006A76ED395 (user_id), INDEX IDX_8E87C00672F5A1AA (channel_id), UNIQUE INDEX UNIQ_8E87C006A76ED39572F5A1AA (user_id, channel_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE channel_read_state (id INT AUTO_INCREMENT NOT NULL, last_read_at DATETIME NOT NULL, user_id INT NOT NULL, channel_id INT NOT NULL, INDEX IDX_4ADAFEB972F5A1AA (channel_id), INDEX IDX_CHANNEL_READ_STATE_USER (user_id), UNIQUE INDEX UNIQ_CHANNEL_READ_STATE_USER_CHANNEL (user_id, channel_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE channel_section (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, position INT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, community_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, INDEX IDX_9A3045EEFDA7B0BF (community_id), INDEX IDX_9A3045EEB03A8386 (created_by_id), INDEX IDX_9A3045EE896DBBDE (updated_by_id), UNIQUE INDEX UNIQ_CHANNEL_SECTION_IDENTIFIER (identifier, community_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE channel_user_preference (id INT AUTO_INCREMENT NOT NULL, level VARCHAR(20) NOT NULL, pin_state VARCHAR(16) DEFAULT NULL, user_id INT NOT NULL, channel_id INT NOT NULL, INDEX IDX_43A40F5C72F5A1AA (channel_id), INDEX IDX_CHANNEL_USER_PREF_USER (user_id), UNIQUE INDEX UNIQ_CHANNEL_USER_PREF_USER_CHANNEL (user_id, channel_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE community (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, is_private TINYINT DEFAULT 0 NOT NULL, hostname VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, accent_color VARCHAR(7) DEFAULT NULL, broadcast_mention_min_role VARCHAR(20) DEFAULT \'member\' NOT NULL, locale VARCHAR(12) DEFAULT \'en\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, welcome_channel_id INT DEFAULT NULL, logo_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, INDEX IDX_1B6040335C68E1EF (welcome_channel_id), UNIQUE INDEX UNIQ_1B604033F98F144A (logo_id), INDEX IDX_1B604033B03A8386 (created_by_id), INDEX IDX_1B604033896DBBDE (updated_by_id), UNIQUE INDEX UNIQ_COMMUNITY_IDENTIFIER (identifier), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE community_emoji (id INT AUTO_INCREMENT NOT NULL, shortcode VARCHAR(36) NOT NULL, name VARCHAR(64) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, community_id INT NOT NULL, image_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, INDEX IDX_CD3B8C76FDA7B0BF (community_id), INDEX IDX_CD3B8C763DA5256D (image_id), INDEX IDX_CD3B8C76B03A8386 (created_by_id), INDEX IDX_CD3B8C76896DBBDE (updated_by_id), UNIQUE INDEX UNIQ_COMMUNITY_EMOJI_SHORTCODE (community_id, shortcode), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE community_invite (id INT AUTO_INCREMENT NOT NULL, token VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME DEFAULT NULL, max_uses INT DEFAULT NULL, use_count INT DEFAULT 0 NOT NULL, community_id INT NOT NULL, created_by_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_B628E5245F37A13B (token), INDEX IDX_B628E524FDA7B0BF (community_id), INDEX IDX_B628E524B03A8386 (created_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE community_member (id INT AUTO_INCREMENT NOT NULL, role VARCHAR(20) NOT NULL, joined_at DATETIME NOT NULL, notifications_muted TINYINT DEFAULT 0 NOT NULL, user_id INT NOT NULL, community_id INT NOT NULL, INDEX IDX_12E0F8BA76ED395 (user_id), INDEX IDX_12E0F8BFDA7B0BF (community_id), UNIQUE INDEX UNIQ_12E0F8BA76ED395FDA7B0BF (user_id, community_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE community_pin (id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, created_at DATETIME NOT NULL, user_id INT NOT NULL, community_id INT NOT NULL, INDEX IDX_85724CCDA76ED395 (user_id), INDEX IDX_85724CCDFDA7B0BF (community_id), INDEX community_pin_user_position_idx (user_id, position), UNIQUE INDEX community_pin_user_community_unique (user_id, community_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE conversation (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(32) NOT NULL, participants_hash VARCHAR(40) NOT NULL, last_message_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_CONVERSATION_IDENTIFIER (identifier), UNIQUE INDEX UNIQ_CONVERSATION_PARTICIPANTS_HASH (participants_hash), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE conversation_member (id INT AUTO_INCREMENT NOT NULL, joined_at DATETIME NOT NULL, muted_until DATETIME DEFAULT NULL, last_read_at DATETIME DEFAULT NULL, conversation_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_422840B89AC0396 (conversation_id), INDEX IDX_CONV_MEMBER_USER (user_id), UNIQUE INDEX UNIQ_CONV_MEMBER_CONV_USER (conversation_id, user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE data_export_request (id INT AUTO_INCREMENT NOT NULL, requested_at DATETIME NOT NULL, status VARCHAR(20) NOT NULL, ready_at DATETIME DEFAULT NULL, expires_at DATETIME DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, file_size INT DEFAULT NULL, download_token VARCHAR(64) DEFAULT NULL, error_message LONGTEXT DEFAULT NULL, user_id INT NOT NULL, INDEX IDX_70102955A76ED395 (user_id), INDEX data_export_user_status_idx (user_id, status), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE group_channel_permission (id INT AUTO_INCREMENT NOT NULL, role VARCHAR(20) NOT NULL, user_group_id INT NOT NULL, channel_id INT NOT NULL, INDEX IDX_7931FA941ED93D47 (user_group_id), INDEX IDX_7931FA9472F5A1AA (channel_id), UNIQUE INDEX UNIQ_7931FA941ED93D4772F5A1AA (user_group_id, channel_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE media_object (id INT AUTO_INCREMENT NOT NULL, file_path VARCHAR(255) DEFAULT NULL, type VARCHAR(20) DEFAULT NULL, original_name VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, size INT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, created_by_id INT DEFAULT NULL, message_id VARCHAR(36) DEFAULT NULL, INDEX IDX_14D43132B03A8386 (created_by_id), INDEX IDX_14D43132537A1329 (message_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE message (id VARCHAR(36) NOT NULL, reactions JSON DEFAULT NULL, mentioned_user_ids JSON DEFAULT NULL, is_deleted TINYINT DEFAULT 0 NOT NULL, kind VARCHAR(16) DEFAULT \'standard\' NOT NULL, created_at DATETIME NOT NULL, pinned_at DATETIME DEFAULT NULL, reply_count INT DEFAULT 0 NOT NULL, last_reply_at DATETIME DEFAULT NULL, purged_attachment_count INT DEFAULT 0 NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, parent_id VARCHAR(36) DEFAULT NULL, deleted_by_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, page_id INT DEFAULT NULL, pinned_by_id INT DEFAULT NULL, INDEX IDX_B6BD307F727ACA70 (parent_id), INDEX IDX_B6BD307FC76F1F52 (deleted_by_id), INDEX IDX_B6BD307FB03A8386 (created_by_id), INDEX IDX_B6BD307F896DBBDE (updated_by_id), INDEX IDX_B6BD307FC4663E4 (page_id), INDEX IDX_B6BD307F59662AC1 (pinned_by_id), INDEX IDX_MESSAGE_PAGE_PARENT (page_id, parent_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE message_body (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_by VARCHAR(255) DEFAULT NULL, updated_at DATETIME NOT NULL, message_id VARCHAR(36) NOT NULL, created_by_id INT DEFAULT NULL, INDEX IDX_723D906B537A1329 (message_id), INDEX IDX_723D906BB03A8386 (created_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE message_page (id INT AUTO_INCREMENT NOT NULL, page_number INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, channel_id INT DEFAULT NULL, conversation_id INT DEFAULT NULL, INDEX IDX_BD9F2DF972F5A1AA (channel_id), INDEX IDX_BD9F2DF99AC0396 (conversation_id), UNIQUE INDEX uniq_message_page_channel_number (channel_id, page_number), UNIQUE INDEX uniq_message_page_conversation_number (conversation_id, page_number), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE moderation_action (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(20) NOT NULL, reason LONGTEXT DEFAULT NULL, expires_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, lifted_at DATETIME DEFAULT NULL, community_id INT NOT NULL, channel_id INT DEFAULT NULL, target_user_id INT NOT NULL, actor_user_id INT NOT NULL, lifted_by_id INT DEFAULT NULL, INDEX IDX_B05D8128FDA7B0BF (community_id), INDEX IDX_B05D812872F5A1AA (channel_id), INDEX IDX_B05D81286C066AFE (target_user_id), INDEX IDX_B05D8128859B83FF (actor_user_id), INDEX IDX_B05D81287A4D02A7 (lifted_by_id), INDEX idx_moderation_target_type_lifted (target_user_id, type, lifted_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE moderator_note (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, community_id INT NOT NULL, target_user_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_37D8562FFDA7B0BF (community_id), INDEX IDX_37D8562F6C066AFE (target_user_id), INDEX IDX_37D8562FF675F31B (author_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, is_read TINYINT NOT NULL, coalesce_key VARCHAR(255) DEFAULT NULL, author_name VARCHAR(255) NOT NULL, channel_identifier VARCHAR(255) NOT NULL, community_identifier VARCHAR(255) NOT NULL, conversation_identifier VARCHAR(32) DEFAULT NULL, message_iri VARCHAR(255) DEFAULT NULL, group_name VARCHAR(100) DEFAULT NULL, group_identifier VARCHAR(100) DEFAULT NULL, reason LONGTEXT DEFAULT NULL, moderation_action_id INT DEFAULT NULL, expires_at DATETIME DEFAULT NULL, emailed_at DATETIME DEFAULT NULL, actor_ids JSON DEFAULT NULL, message_count INT DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, recipient_id INT NOT NULL, community_id INT DEFAULT NULL, INDEX IDX_BF5476CAE92F8F78 (recipient_id), INDEX IDX_BF5476CAFDA7B0BF (community_id), INDEX idx_notification_recipient_read (recipient_id, is_read), UNIQUE INDEX uniq_notification_coalesce_key (coalesce_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE presence_sample (id INT AUTO_INCREMENT NOT NULL, members_online INT NOT NULL, guests_online INT NOT NULL, sampled_at DATETIME NOT NULL, community_id INT NOT NULL, INDEX IDX_1C9AC7D3FDA7B0BF (community_id), INDEX idx_presence_sample_community_time (community_id, sampled_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE profile (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, bio VARCHAR(190) DEFAULT NULL, location VARCHAR(100) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, birthday_month SMALLINT DEFAULT NULL, birthday_day SMALLINT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, user_id INT NOT NULL, avatar_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_8157AA0FA76ED395 (user_id), UNIQUE INDEX UNIQ_8157AA0F86383B10 (avatar_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE push_subscription (id INT AUTO_INCREMENT NOT NULL, endpoint VARCHAR(512) NOT NULL, p256dh VARCHAR(255) NOT NULL, auth_token VARCHAR(255) NOT NULL, locale VARCHAR(8) DEFAULT \'en\' NOT NULL, created_at DATETIME NOT NULL, user_id INT NOT NULL, INDEX IDX_PUSH_SUBSCRIPTION_USER (user_id), UNIQUE INDEX UNIQ_PUSH_SUBSCRIPTION_ENDPOINT (endpoint), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE reaction (id INT AUTO_INCREMENT NOT NULL, emoji VARCHAR(64) NOT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, message_id VARCHAR(36) NOT NULL, created_by_id INT DEFAULT NULL, INDEX IDX_A4D707F7537A1329 (message_id), INDEX IDX_A4D707F7B03A8386 (created_by_id), UNIQUE INDEX UNIQ_REACTION_MSG_USER_EMOJI (message_id, created_by_id, emoji), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, id INT AUTO_INCREMENT NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE report (id INT AUTO_INCREMENT NOT NULL, message_text_snapshot LONGTEXT DEFAULT NULL, category VARCHAR(20) NOT NULL, comment LONGTEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, resolved_at DATETIME DEFAULT NULL, resolution_note LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, reporter_id INT DEFAULT NULL, community_id INT DEFAULT NULL, message_id VARCHAR(36) DEFAULT NULL, reported_user_id INT NOT NULL, resolved_by_id INT DEFAULT NULL, INDEX IDX_C42F7784E1CFE6F5 (reporter_id), INDEX IDX_C42F7784FDA7B0BF (community_id), INDEX IDX_C42F7784537A1329 (message_id), INDEX IDX_C42F7784E7566E (reported_user_id), INDEX IDX_C42F77846713A32B (resolved_by_id), INDEX idx_report_community_status (community_id, status), INDEX idx_report_status (status), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, expires_at DATETIME NOT NULL, used_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_7CE748AE7927C745F37A13B (email, token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE setting (`key` VARCHAR(191) NOT NULL, value JSON DEFAULT NULL, updated_at DATETIME NOT NULL, updated_by_id INT DEFAULT NULL, INDEX IDX_9F74B898896DBBDE (updated_by_id), PRIMARY KEY (`key`)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE two_factor_recovery_code (id INT AUTO_INCREMENT NOT NULL, code_hash VARCHAR(64) NOT NULL, used_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, user_id INT NOT NULL, INDEX IDX_36B66B7FA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, is_bot TINYINT DEFAULT 0 NOT NULL, email_notifications TINYINT DEFAULT 0 NOT NULL, locale VARCHAR(8) DEFAULT \'en\' NOT NULL, deletion_requested_at DATETIME DEFAULT NULL, onboarded_at DATETIME DEFAULT NULL, terms_accepted_at DATETIME DEFAULT NULL, age_verified_at DATETIME DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, two_factor_secret VARCHAR(255) DEFAULT NULL, totp_enabled_at DATETIME DEFAULT NULL, totp_last_used_timestep INT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE user_group (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(100) NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(10) DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, is_hidden TINYINT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, community_id INT NOT NULL, owner_id INT DEFAULT NULL, INDEX IDX_8F02BF9DFDA7B0BF (community_id), INDEX IDX_8F02BF9D7E3C61F9 (owner_id), UNIQUE INDEX UNIQ_8F02BF9DFDA7B0BF772E836A (community_id, identifier), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE user_group_member (id INT AUTO_INCREMENT NOT NULL, added_at DATETIME NOT NULL, user_id INT NOT NULL, user_group_id INT NOT NULL, INDEX IDX_23AE5EAAA76ED395 (user_id), INDEX IDX_23AE5EAA1ED93D47 (user_group_id), UNIQUE INDEX UNIQ_23AE5EAAA76ED3951ED93D47 (user_id, user_group_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE user_preference (id INT AUTO_INCREMENT NOT NULL, theme VARCHAR(16) DEFAULT NULL, submit_key VARCHAR(16) DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, send_typing_indicator TINYINT DEFAULT NULL, desktop_notifications TINYINT DEFAULT NULL, convert_emoticons TINYINT DEFAULT NULL, resume_last_location TINYINT DEFAULT NULL, section_collapse JSON DEFAULT NULL, updated_at DATETIME NOT NULL, user_id INT NOT NULL, UNIQUE INDEX UNIQ_FA0E76BFA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE webhook (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, url VARCHAR(2048) NOT NULL, trigger_key VARCHAR(64) NOT NULL, filters JSON DEFAULT NULL, secret VARCHAR(80) NOT NULL, is_active TINYINT NOT NULL, disabled_reason VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, created_by_id INT DEFAULT NULL, INDEX IDX_8A741756B03A8386 (created_by_id), INDEX IDX_8A7417568EAB6907 (trigger_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE webhook_delivery (id INT AUTO_INCREMENT NOT NULL, trigger_key VARCHAR(64) NOT NULL, request_payload JSON NOT NULL, status VARCHAR(16) NOT NULL, http_code INT DEFAULT NULL, response_body LONGTEXT DEFAULT NULL, error VARCHAR(255) DEFAULT NULL, attempts INT NOT NULL, duration_ms INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, webhook_id INT NOT NULL, actor_id INT DEFAULT NULL, INDEX IDX_C97B6A385C9BA60B (webhook_id), INDEX IDX_C97B6A3810DAF24A (actor_id), INDEX IDX_C97B6A388B8E8428 (created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE admin_audit_log ADD CONSTRAINT FK_1F16C5C710DAF24A FOREIGN KEY (actor_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE api_key ADD CONSTRAINT FK_C912ED9DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appeal ADD CONSTRAINT FK_96794351675D569B FOREIGN KEY (moderation_action_id) REFERENCES moderation_action (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appeal ADD CONSTRAINT FK_96794351851858D7 FOREIGN KEY (appellant_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appeal ADD CONSTRAINT FK_967943516713A32B FOREIGN KEY (resolved_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE channel ADD CONSTRAINT FK_A2F98E47D823E37A FOREIGN KEY (section_id) REFERENCES channel_section (id)');
        $this->addSql('ALTER TABLE channel ADD CONSTRAINT FK_A2F98E47FDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id)');
        $this->addSql('ALTER TABLE channel_member ADD CONSTRAINT FK_8E87C006A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE channel_member ADD CONSTRAINT FK_8E87C00672F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE channel_read_state ADD CONSTRAINT FK_4ADAFEB9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE channel_read_state ADD CONSTRAINT FK_4ADAFEB972F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE channel_section ADD CONSTRAINT FK_9A3045EEFDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id)');
        $this->addSql('ALTER TABLE channel_section ADD CONSTRAINT FK_9A3045EEB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE channel_section ADD CONSTRAINT FK_9A3045EE896DBBDE FOREIGN KEY (updated_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE channel_user_preference ADD CONSTRAINT FK_43A40F5CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE channel_user_preference ADD CONSTRAINT FK_43A40F5C72F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community ADD CONSTRAINT FK_1B6040335C68E1EF FOREIGN KEY (welcome_channel_id) REFERENCES channel (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE community ADD CONSTRAINT FK_1B604033F98F144A FOREIGN KEY (logo_id) REFERENCES media_object (id)');
        $this->addSql('ALTER TABLE community ADD CONSTRAINT FK_1B604033B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE community ADD CONSTRAINT FK_1B604033896DBBDE FOREIGN KEY (updated_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE community_emoji ADD CONSTRAINT FK_CD3B8C76FDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_emoji ADD CONSTRAINT FK_CD3B8C763DA5256D FOREIGN KEY (image_id) REFERENCES media_object (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE community_emoji ADD CONSTRAINT FK_CD3B8C76B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE community_emoji ADD CONSTRAINT FK_CD3B8C76896DBBDE FOREIGN KEY (updated_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE community_invite ADD CONSTRAINT FK_B628E524FDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_invite ADD CONSTRAINT FK_B628E524B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE community_member ADD CONSTRAINT FK_12E0F8BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_member ADD CONSTRAINT FK_12E0F8BFDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_pin ADD CONSTRAINT FK_85724CCDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_pin ADD CONSTRAINT FK_85724CCDFDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation_member ADD CONSTRAINT FK_422840B89AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation_member ADD CONSTRAINT FK_422840B8A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE data_export_request ADD CONSTRAINT FK_70102955A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_channel_permission ADD CONSTRAINT FK_7931FA941ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_channel_permission ADD CONSTRAINT FK_7931FA9472F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_object ADD CONSTRAINT FK_14D43132B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE media_object ADD CONSTRAINT FK_14D43132537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F727ACA70 FOREIGN KEY (parent_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FC4663E4 FOREIGN KEY (page_id) REFERENCES message_page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F59662AC1 FOREIGN KEY (pinned_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message_body ADD CONSTRAINT FK_723D906B537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_body ADD CONSTRAINT FK_723D906BB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message_page ADD CONSTRAINT FK_BD9F2DF972F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id)');
        $this->addSql('ALTER TABLE message_page ADD CONSTRAINT FK_BD9F2DF99AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE moderation_action ADD CONSTRAINT FK_B05D8128FDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderation_action ADD CONSTRAINT FK_B05D812872F5A1AA FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE moderation_action ADD CONSTRAINT FK_B05D81286C066AFE FOREIGN KEY (target_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderation_action ADD CONSTRAINT FK_B05D8128859B83FF FOREIGN KEY (actor_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderation_action ADD CONSTRAINT FK_B05D81287A4D02A7 FOREIGN KEY (lifted_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE moderator_note ADD CONSTRAINT FK_37D8562FFDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderator_note ADD CONSTRAINT FK_37D8562F6C066AFE FOREIGN KEY (target_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderator_note ADD CONSTRAINT FK_37D8562FF675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAFDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id)');
        $this->addSql('ALTER TABLE presence_sample ADD CONSTRAINT FK_1C9AC7D3FDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0F86383B10 FOREIGN KEY (avatar_id) REFERENCES media_object (id)');
        $this->addSql('ALTER TABLE push_subscription ADD CONSTRAINT FK_562830F3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reaction ADD CONSTRAINT FK_A4D707F7537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reaction ADD CONSTRAINT FK_A4D707F7B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784FDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E7566E FOREIGN KEY (reported_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F77846713A32B FOREIGN KEY (resolved_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898896DBBDE FOREIGN KEY (updated_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE two_factor_recovery_code ADD CONSTRAINT FK_36B66B7FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9DFDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_group_member ADD CONSTRAINT FK_23AE5EAAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group_member ADD CONSTRAINT FK_23AE5EAA1ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_FA0E76BFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE webhook ADD CONSTRAINT FK_8A741756B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE webhook_delivery ADD CONSTRAINT FK_C97B6A385C9BA60B FOREIGN KEY (webhook_id) REFERENCES webhook (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE webhook_delivery ADD CONSTRAINT FK_C97B6A3810DAF24A FOREIGN KEY (actor_id) REFERENCES user (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE admin_audit_log DROP FOREIGN KEY FK_1F16C5C710DAF24A');
        $this->addSql('ALTER TABLE api_key DROP FOREIGN KEY FK_C912ED9DA76ED395');
        $this->addSql('ALTER TABLE appeal DROP FOREIGN KEY FK_96794351675D569B');
        $this->addSql('ALTER TABLE appeal DROP FOREIGN KEY FK_96794351851858D7');
        $this->addSql('ALTER TABLE appeal DROP FOREIGN KEY FK_967943516713A32B');
        $this->addSql('ALTER TABLE channel DROP FOREIGN KEY FK_A2F98E47D823E37A');
        $this->addSql('ALTER TABLE channel DROP FOREIGN KEY FK_A2F98E47FDA7B0BF');
        $this->addSql('ALTER TABLE channel_member DROP FOREIGN KEY FK_8E87C006A76ED395');
        $this->addSql('ALTER TABLE channel_member DROP FOREIGN KEY FK_8E87C00672F5A1AA');
        $this->addSql('ALTER TABLE channel_read_state DROP FOREIGN KEY FK_4ADAFEB9A76ED395');
        $this->addSql('ALTER TABLE channel_read_state DROP FOREIGN KEY FK_4ADAFEB972F5A1AA');
        $this->addSql('ALTER TABLE channel_section DROP FOREIGN KEY FK_9A3045EEFDA7B0BF');
        $this->addSql('ALTER TABLE channel_section DROP FOREIGN KEY FK_9A3045EEB03A8386');
        $this->addSql('ALTER TABLE channel_section DROP FOREIGN KEY FK_9A3045EE896DBBDE');
        $this->addSql('ALTER TABLE channel_user_preference DROP FOREIGN KEY FK_43A40F5CA76ED395');
        $this->addSql('ALTER TABLE channel_user_preference DROP FOREIGN KEY FK_43A40F5C72F5A1AA');
        $this->addSql('ALTER TABLE community DROP FOREIGN KEY FK_1B6040335C68E1EF');
        $this->addSql('ALTER TABLE community DROP FOREIGN KEY FK_1B604033F98F144A');
        $this->addSql('ALTER TABLE community DROP FOREIGN KEY FK_1B604033B03A8386');
        $this->addSql('ALTER TABLE community DROP FOREIGN KEY FK_1B604033896DBBDE');
        $this->addSql('ALTER TABLE community_emoji DROP FOREIGN KEY FK_CD3B8C76FDA7B0BF');
        $this->addSql('ALTER TABLE community_emoji DROP FOREIGN KEY FK_CD3B8C763DA5256D');
        $this->addSql('ALTER TABLE community_emoji DROP FOREIGN KEY FK_CD3B8C76B03A8386');
        $this->addSql('ALTER TABLE community_emoji DROP FOREIGN KEY FK_CD3B8C76896DBBDE');
        $this->addSql('ALTER TABLE community_invite DROP FOREIGN KEY FK_B628E524FDA7B0BF');
        $this->addSql('ALTER TABLE community_invite DROP FOREIGN KEY FK_B628E524B03A8386');
        $this->addSql('ALTER TABLE community_member DROP FOREIGN KEY FK_12E0F8BA76ED395');
        $this->addSql('ALTER TABLE community_member DROP FOREIGN KEY FK_12E0F8BFDA7B0BF');
        $this->addSql('ALTER TABLE community_pin DROP FOREIGN KEY FK_85724CCDA76ED395');
        $this->addSql('ALTER TABLE community_pin DROP FOREIGN KEY FK_85724CCDFDA7B0BF');
        $this->addSql('ALTER TABLE conversation_member DROP FOREIGN KEY FK_422840B89AC0396');
        $this->addSql('ALTER TABLE conversation_member DROP FOREIGN KEY FK_422840B8A76ED395');
        $this->addSql('ALTER TABLE data_export_request DROP FOREIGN KEY FK_70102955A76ED395');
        $this->addSql('ALTER TABLE group_channel_permission DROP FOREIGN KEY FK_7931FA941ED93D47');
        $this->addSql('ALTER TABLE group_channel_permission DROP FOREIGN KEY FK_7931FA9472F5A1AA');
        $this->addSql('ALTER TABLE media_object DROP FOREIGN KEY FK_14D43132B03A8386');
        $this->addSql('ALTER TABLE media_object DROP FOREIGN KEY FK_14D43132537A1329');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F727ACA70');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FC76F1F52');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FB03A8386');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F896DBBDE');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FC4663E4');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F59662AC1');
        $this->addSql('ALTER TABLE message_body DROP FOREIGN KEY FK_723D906B537A1329');
        $this->addSql('ALTER TABLE message_body DROP FOREIGN KEY FK_723D906BB03A8386');
        $this->addSql('ALTER TABLE message_page DROP FOREIGN KEY FK_BD9F2DF972F5A1AA');
        $this->addSql('ALTER TABLE message_page DROP FOREIGN KEY FK_BD9F2DF99AC0396');
        $this->addSql('ALTER TABLE moderation_action DROP FOREIGN KEY FK_B05D8128FDA7B0BF');
        $this->addSql('ALTER TABLE moderation_action DROP FOREIGN KEY FK_B05D812872F5A1AA');
        $this->addSql('ALTER TABLE moderation_action DROP FOREIGN KEY FK_B05D81286C066AFE');
        $this->addSql('ALTER TABLE moderation_action DROP FOREIGN KEY FK_B05D8128859B83FF');
        $this->addSql('ALTER TABLE moderation_action DROP FOREIGN KEY FK_B05D81287A4D02A7');
        $this->addSql('ALTER TABLE moderator_note DROP FOREIGN KEY FK_37D8562FFDA7B0BF');
        $this->addSql('ALTER TABLE moderator_note DROP FOREIGN KEY FK_37D8562F6C066AFE');
        $this->addSql('ALTER TABLE moderator_note DROP FOREIGN KEY FK_37D8562FF675F31B');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAFDA7B0BF');
        $this->addSql('ALTER TABLE presence_sample DROP FOREIGN KEY FK_1C9AC7D3FDA7B0BF');
        $this->addSql('ALTER TABLE profile DROP FOREIGN KEY FK_8157AA0FA76ED395');
        $this->addSql('ALTER TABLE profile DROP FOREIGN KEY FK_8157AA0F86383B10');
        $this->addSql('ALTER TABLE push_subscription DROP FOREIGN KEY FK_562830F3A76ED395');
        $this->addSql('ALTER TABLE reaction DROP FOREIGN KEY FK_A4D707F7537A1329');
        $this->addSql('ALTER TABLE reaction DROP FOREIGN KEY FK_A4D707F7B03A8386');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784FDA7B0BF');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784537A1329');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784E7566E');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F77846713A32B');
        $this->addSql('ALTER TABLE setting DROP FOREIGN KEY FK_9F74B898896DBBDE');
        $this->addSql('ALTER TABLE two_factor_recovery_code DROP FOREIGN KEY FK_36B66B7FA76ED395');
        $this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_8F02BF9DFDA7B0BF');
        $this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_8F02BF9D7E3C61F9');
        $this->addSql('ALTER TABLE user_group_member DROP FOREIGN KEY FK_23AE5EAAA76ED395');
        $this->addSql('ALTER TABLE user_group_member DROP FOREIGN KEY FK_23AE5EAA1ED93D47');
        $this->addSql('ALTER TABLE user_preference DROP FOREIGN KEY FK_FA0E76BFA76ED395');
        $this->addSql('ALTER TABLE webhook DROP FOREIGN KEY FK_8A741756B03A8386');
        $this->addSql('ALTER TABLE webhook_delivery DROP FOREIGN KEY FK_C97B6A385C9BA60B');
        $this->addSql('ALTER TABLE webhook_delivery DROP FOREIGN KEY FK_C97B6A3810DAF24A');
        $this->addSql('DROP TABLE admin_audit_log');
        $this->addSql('DROP TABLE api_key');
        $this->addSql('DROP TABLE appeal');
        $this->addSql('DROP TABLE challenge');
        $this->addSql('DROP TABLE channel');
        $this->addSql('DROP TABLE channel_member');
        $this->addSql('DROP TABLE channel_read_state');
        $this->addSql('DROP TABLE channel_section');
        $this->addSql('DROP TABLE channel_user_preference');
        $this->addSql('DROP TABLE community');
        $this->addSql('DROP TABLE community_emoji');
        $this->addSql('DROP TABLE community_invite');
        $this->addSql('DROP TABLE community_member');
        $this->addSql('DROP TABLE community_pin');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_member');
        $this->addSql('DROP TABLE data_export_request');
        $this->addSql('DROP TABLE group_channel_permission');
        $this->addSql('DROP TABLE media_object');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE message_body');
        $this->addSql('DROP TABLE message_page');
        $this->addSql('DROP TABLE moderation_action');
        $this->addSql('DROP TABLE moderator_note');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE presence_sample');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE push_subscription');
        $this->addSql('DROP TABLE reaction');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE two_factor_recovery_code');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE user_group_member');
        $this->addSql('DROP TABLE user_preference');
        $this->addSql('DROP TABLE webhook');
        $this->addSql('DROP TABLE webhook_delivery');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
